momentohq/client-sdk-ruby

lib/momento/get_response.rb
spec/momento/get_response_spec.rb

`get` is docuented to return a GetResponse. IDEs won't see it if it's only in a subclass. Add it to GetResponse.
Closes #44

feature: Make #value discoverable

---

lib/momento/create_cache_response_builder.rb
lib/momento/delete_cache_response_builder.rb
lib/momento/delete_response_builder.rb
lib/momento/get_response_builder.rb
lib/momento/list_caches_response_builder.rb
lib/momento/response/error.rb
lib/momento/set_response_builder.rb
lib/momento/simple_cache_client.rb
spec/factories/momento/response.rb
spec/momento/simple_cache_client_spec.rb
spec/support/shared_examples/momento/response/from_block.rb
spec/support/shared_examples/momento/response_builder.rb

Some misc refactorings to cut down the complexity of #6.
* Remove unused test factory response traits.
* Rename grpc_exception -> exception, we no longer assume it is a GRPC exception.

refactor: Misc refactor cleanups

---

spec/momento/create_cache_response/already_exists_spec.rb
spec/momento/create_cache_response/error_spec.rb
spec/momento/create_cache_response/success_spec.rb
spec/momento/create_cache_response_spec.rb
spec/momento/delete_cache_response/error_spec.rb
spec/momento/delete_cache_response/success_spec.rb
spec/momento/delete_cache_response_spec.rb
spec/momento/delete_response/error_spec.rb
spec/momento/delete_response/success_spec.rb
spec/momento/delete_response_spec.rb
spec/momento/get_response/error_spec.rb
spec/momento/get_response/hit_spec.rb
spec/momento/get_response/miss_spec.rb
spec/momento/get_response_spec.rb
spec/momento/list_caches_response/error_spec.rb
spec/momento/list_caches_response/success_spec.rb
spec/momento/list_caches_response_spec.rb
spec/momento/set_response/error_spec.rb
spec/momento/set_response/success_spec.rb
spec/momento/set_response_spec.rb
spec/support/shared_examples/momento/create_cache_response.rb
spec/support/shared_examples/momento/delete_cache_response.rb
spec/support/shared_examples/momento/delete_response.rb
spec/support/shared_examples/momento/get_response.rb
spec/support/shared_examples/momento/list_caches_response.rb
spec/support/shared_examples/momento/response.rb
spec/support/shared_examples/momento/set_response.rb

Removes duplicate code from the individual TypeResponse shared examples. Lets us consistently check Momento::Response behavior.
This will make #6 simpler and the eventual PR easier to review.
Also:
* Make the shared let names more descriptive.
* Make more use of the attribute check.

test: Push checking common Momento::Response attributes down.

---

README.md
examples/basic.rb
lib/momento/create_cache_response_builder.rb
lib/momento/delete_cache_response_builder.rb
lib/momento/delete_response_builder.rb
lib/momento/error.rb
lib/momento/error/grpc_details.rb
lib/momento/error/transport_details.rb
lib/momento/error/types.rb
lib/momento/error_builder.rb
lib/momento/get_response_builder.rb
lib/momento/list_caches_response_builder.rb
lib/momento/response.rb
lib/momento/response/error.rb
lib/momento/set_response_builder.rb
lib/momento/simple_cache_client.rb
spec/momento/create_cache_response/error_spec.rb
spec/momento/delete_cache_response/error_spec.rb
spec/momento/delete_response/error_spec.rb
spec/momento/error/types_spec.rb
spec/momento/error_builder_spec.rb
spec/momento/error_spec.rb
spec/momento/get_response/error_spec.rb
spec/momento/list_caches_response/error_spec.rb
spec/momento/set_response/error_spec.rb
spec/momento/simple_cache_client_spec.rb
spec/support/matchers/be_a_momento_error.rb
spec/support/shared_examples/momento/response.rb
spec/support/shared_examples/momento/response/from_block.rb
spec/support/shared_examples/momento/response_builder.rb

Fully implements [Momento Client SDKs Specification: Error Handling](https://github.com/momentohq/standards-and-practices/blob/main/docs/client-specifications/error-handling.md), except "Our response objects are always safely printable" which will be in #27.
- Ruby does't have enums. MomentoErrorCode is implemented as subclasses with an error_code method.
- Momento::Response::Error#exception was removed breaking the v0.1.0 interface.
Closes #6

BREAKING CHANGE: Standards & Practices error handling

---

lib/momento/get_response.rb
lib/momento/list_caches_response.rb
lib/momento/response.rb
lib/momento/response/error.rb
lib/momento/set_response.rb
lib/momento/set_response_builder.rb
spec/factories/momento/set_response.rb
spec/momento/create_cache_response/error_spec.rb
spec/momento/delete_cache_response/error_spec.rb
spec/momento/delete_response/error_spec.rb
spec/momento/get_response/error_spec.rb
spec/momento/get_response/hit_spec.rb
spec/momento/list_caches_response/error_spec.rb
spec/momento/list_caches_response/success_spec.rb
spec/momento/set_response/error_spec.rb
spec/momento/set_response/success_spec.rb
spec/momento/set_response_builder_spec.rb
spec/support/shared_examples/momento/response.rb
spec/support/shared_examples/momento/response/error.rb

I took the behavior from the PHP client.
The breaking change is previously a Hit would stringify to the complete value.
Closes #27

BREAKING_CHANGE: Consistently stringify responses

---

lib/momento/create_cache_response_builder.rb
lib/momento/delete_cache_response_builder.rb
lib/momento/delete_response_builder.rb
lib/momento/error_builder.rb
lib/momento/exceptions.rb
lib/momento/get_response_builder.rb
lib/momento/response_builder.rb
lib/momento/set_response_builder.rb
lib/momento/simple_cache_client.rb
spec/live_spec.rb
spec/momento/simple_cache_client_spec.rb

- nil and non-String keys, values, and cache names as TypeErrors.
- Non-ASCII cache names are an InvalidArgument response.
There is a broad refactoring of `spec/momento/simple_cache_client_spec.rb` to make it easier to test the validation consistently. It might be easier to review this as individual commits.
Closes #41 
Closes #37 
Closes #66 
Closes #34

Handle invalid keys, values, and cache names.

---

lib/momento/error_builder.rb

It used to exist, not anymore.

fix: Referring to a method that does not exist.

---

README.md
examples/basic.rb
lib/momento/get_response.rb
spec/live_spec.rb
spec/momento/get_response/hit_spec.rb
spec/momento/get_response_builder_spec.rb
spec/momento/simple_cache_client_spec.rb
spec/support/shared_examples/momento/get_response.rb

Nobody likes messing with string encoding. Rather than explain it and risk bugs and frustration, just do it for the user. The PHP client does the same thing.
Closes #82

BREAKING_CHANGE: Split GetResponse::Hit.value into value_bytes and value_string

---

.github/workflows/test.yml

Change the versions in the github test action to strings. They were being treated as numbers and so the 3.0 was changing to a 3, making the tests use the latest version of Ruby.

fix: change the ruby versions in the test action to strings

---

Gemfile.lock
README.md
examples/compact.rb
examples/example.rb
examples/file.rb
lib/momento.rb
lib/momento/auth/credential_provider.rb
lib/momento/simple_cache_client.rb
momento.gemspec
sig/momento/auth/credential_provider.rbs
spec/factories/credential_provider.rb
spec/factories/simple_cache_client.rb
spec/live_spec.rb
spec/momento/credential_provider_spec.rb
spec/momento/simple_cache_client_spec.rb

Create a CredentialProvider class that parses legacy/v1 tokens from the command line or a string.
Make SimpleCacheClient take a CredentialProvider.
Update the examples with the new constructor.
Fix some RuboCop issues.

feat: add a CredentialProvider

---

.github/workflows/on-pull-request.yml
.github/workflows/on-push-to-main.yml
README.template.md

Addresses #132 
Don't want main branch to keep failing one check that's intended for only on-pull-request workflows

chore: split github actions workflows into on-pull-request and on-push-to-main

---

lib/momento/error/types.rb
spec/momento/error/types_spec.rb

This commit adds the `ConnectionError`. It is currently unused but is likely to be needed in the future.

chore: add ConnectionError

---

lib/momento/cache_client.rb
lib/momento/get_response.rb
spec/momento/get_response/hit_spec.rb

Ensure that strings being sent to Momento are UTF-8 encoded, unless they represent binary data. This prevents getting an error when the Ruby client with a non-UTF-8 default tries to read a UTF-8 string from the server.

chore: always encode strings as UTF-8

---

examples/compact.rb
examples/example.rb
lib/momento/cache_client.rb
lib/momento/list_caches_response.rb
sig/momento/list_caches_response.rbs
spec/momento/cache_client_spec.rb

Remove the caches method. Since pagination doesn't exist yet, it doesn't do anything other than providing a slightly different version of the list_caches method.

chore: Remove the caches method

---

examples/compact.rb
examples/example.rb
lib/momento.rb
lib/momento/cache_client.rb
lib/momento/collection_ttl.rb
lib/momento/response.rb
lib/momento/response/sort_order.rb
lib/momento/response/sorted_set/sorted_set_fetch_response.rb
lib/momento/response/sorted_set/sorted_set_put_element_response.rb
lib/momento/response/sorted_set/sorted_set_put_elements_response.rb
sig/momento/cache_client.rbs
sig/momento/collection_ttl.rbs
sig/momento/sorted_set_fetch_response.rbs
sig/momento/sorted_set_put_element_response.rbs
sig/momento/sorted_set_put_elements_response.rbs
spec/integration/momento/cache_client_sorted_set_spec.rb

Add sorted set put element and put elements. Put elements can take in the sorted set in a variety of formats.
Add sorted set fetch by score. It returns its result as an array of hashes [{value: "value", score: 1.0}].
Fix some rubocop warnings

feat: add sorted set put and fetch by score

---

lib/momento/cache_client.rb
spec/integration/shared_examples.rb
spec/momento/cache_client_spec.rb

Update the validate_cache_name function to return a UTF-8 encoded version of the cache name. If it already is UTF-8, this won't do anything. If it contains bytes that can't be encoded in UTF-8, it raises an error.
Use the result of validate_cache_name in the cache functions.

feat: support UTF-8 cache names instead of just ASCII

---

lib/momento/cache_client.rb
lib/momento/config/configuration.rb
lib/momento/config/transport/grpc_configuration.rb
lib/momento/config/transport/static_transport_strategy.rb
lib/momento/config/transport/transport_strategy.rb
sig/momento/config/configuration.rbs
sig/momento/config/transport/grpc_configuration.rbs
spec/momento/cache_client_spec.rb

This commit does the following:
* Fix the configuration modifier methods in the classes in the config tree; they were using `self.` methods, which are actually static methods
* Add support for configuring the number of grpc channels.
Tested the grpc channel support by modifying the example code and using `lsof`.

feat: add support for multiple grpc channels, fix configuration modifiers

---

lib/momento/cache_client.rb
sig/momento/cache_client.rbs
spec/momento/cache_client_spec.rb

This commit does the following:
* Updates the code so that the agent header is only sent on the first request
* Adds the runtime-version header to report the ruby version
* adds the ":cache:" to the agent header to identify which client

feat: add runtime version header, only send agent headers on first request

---

.github/workflows/release-please.yml
examples/Gemfile

Update to the non-deprecated release please action
Remove unnecessary debugging step.
Update the examples momento SDK to the latest version.

fix: only configure git in release please if the repo was checked out

---

lib/momento/cache_client.rb
spec/momento/cache_client_spec.rb

- Based on the commit [here](https://github.com/googleapis/gax-ruby/pull/213/files), dynamic txt lookup for dns resolution flag is disabled by default in grpc-ruby.
- This commit explicitly disables it too.
```
sudo tcpdump -i any -vvv port 53 | grep -i cache.cell-alpha-dev.preprod.a.momentohq.com           ─╯
Password:
tcpdump: data link type PKTAP
tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), snapshot length 524288 bytes
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.63435: [udp sum ok] 47488 q: A? control.cell-alpha-dev.preprod.a.momentohq.com. 2/0/0 control.cell-alpha-dev.preprod.a.momentohq.com. [5m] CNAME cache.cell-alpha-dev.preprod.a.momentohq.com., cache.cell-alpha-dev.preprod.a.momentohq.com. [1m] A 54.186.170.81 (100)
pd1nsc3.st.vc.shawcable.net.domain > …
```

fix: disable dynamic DNS service config
